import { Imobile } from "../models/mobile";


export let mobileProducts: Array<Imobile> = [
  {
    id: 1,
    name: 'iPhone 13',
    brand: 'Apple',
    price: 999,
    image:
      'https://i.insider.com/6116b065c040ad0018ce3ea1?width=1009&format=jpeg',
    isAvailable: true,
    rating: 4.9,
    noOfItems: 50,
    specifications: [
      '6.1-inch OLED Display',
      'A15 Bionic Chip',
      'Dual 12MP Cameras',
      '5G Connectivity',
      'Face ID',
    ],
  },
  {
    id: 2,
    name: 'Samsung Galaxy S21',
    brand: 'Samsung',
    price: 899,
    image: '',
    isAvailable: false,
    rating: 4.5,
    noOfItems: 20,
    specifications: [
      '6.2-inch AMOLED Display',
      'Exynos 2100 / Snapdragon 888',
      'Triple Camera System',
      '120Hz Refresh Rate',
      'Wireless Charging',
    ],
  },
  {
    id: 3,
    name: 'Google Pixel 6',
    brand: 'Google',
    price: 799,
    image:
      'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios16-iphone13-pro-widgets-home-screen.png',
    isAvailable: false,
    rating: 3.9,
    noOfItems: 10,
    specifications: [
      '6.4-inch OLED Display',
      'Google Tensor Chip',
      '50MP Main Camera',
      'Android 12',
      'Titan M2 Security',
    ],
  },
  {
    id: 4,
    name: 'OnePlus 9 Pro',
    brand: 'OnePlus',
    price: 899,
    image: '',
    isAvailable: true,
    rating: 2.9,
    noOfItems: 7,
    specifications: [
      '6.7-inch Fluid AMOLED',
      'Snapdragon 888',
      'Hasselblad Quad Camera',
      '65W Fast Charging',
      '5G Connectivity',
    ],
  },
  {
    id: 5,
    name: 'Xiaomi Mi 11',
    brand: 'Xiaomi',
    price: 699,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
    isAvailable: true,
    rating: 4.8,
    noOfItems: 5,
    specifications: [
      '6.81-inch AMOLED',
      'Snapdragon 888',
      '108MP Main Camera',
      '4600mAh Battery',
      '120Hz Refresh Rate',
    ],
  },
  {
    id: 6,
    name: 'Sony Xperia 1 III',
    brand: 'Sony',
    price: 1199,
    image: '',
    isAvailable: true,
    rating: 2.5,
    noOfItems: 100,
    specifications: [
      '6.5-inch 4K OLED',
      'Snapdragon 888',
      'Triple 12MP Camera',
      '120Hz Refresh Rate',
      '360 Reality Audio',
    ],
  },
  {
    id: 7,
    name: 'LG Velvet',
    brand: 'LG',
    price: 599,
    image: '',
    isAvailable: false,
    rating: 1.5,
    noOfItems: 2,
    specifications: [
      '6.8-inch P-OLED',
      'Snapdragon 765G',
      '48MP Camera',
      '4300mAh Battery',
      'Stylus Support',
    ],
  },
  {
    id: 8,
    name: 'Huawei P40 Pro',
    brand: 'Huawei',
    price: 899,
    image: '',
    isAvailable: true,
    rating: 3.5,
    noOfItems: 45,
    specifications: [
      '6.58-inch OLED',
      'Kirin 990 5G',
      'Quad Camera System',
      '4200mAh Battery',
      'Wireless Charging',
    ],
  },
  {
    id: 9,
    name: 'Motorola Moto G Power',
    brand: 'Motorola',
    price: 249,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
    isAvailable: true,
    rating: 4.5,
    noOfItems: 500,
    specifications: [
      '6.6-inch IPS LCD',
      'Snapdragon 662',
      '5000mAh Battery',
      'Triple Camera Setup',
      'Android 11',
    ],
  },
  {
    id: 10,
    name: 'Nokia 8.3',
    brand: 'Nokia',
    price: 499,
    image: '',
    isAvailable: true,
    rating: 4.5,
    noOfItems: 8,
    specifications: [
      '6.81-inch IPS LCD',
      'Snapdragon 765G',
      '64MP Camera',
      '5G Connectivity',
      '4500mAh Battery',
    ],
  },
];
