import { Iplayer } from "../models/player";


export const cricketPlayers: Array<Iplayer> = [
  {
    name: 'Virat Kohli',
    team: 'India',
    odiRuns: 12898,
    testRuns: 8848,
    debutYear: 2008,
  },
  {
    name: 'Joe Root',
    team: 'England',
    odiRuns: 6207,
    testRuns: 11528,
    debutYear: 2012,
  },
  {
    name: 'Steve Smith',
    team: 'Australia',
    odiRuns: 5050,
    testRuns: 9471,
    debutYear: 2010,
  },
  {
    name: 'Kane Williamson',
    team: 'New Zealand',
    odiRuns: 6554,
    testRuns: 8124,
    debutYear: 2010,
  },
  {
    name: 'David Warner',
    team: 'Australia',
    odiRuns: 6932,
    testRuns: 8786,
    debutYear: 2009,
  },
  {
    name: 'Ben Stokes',
    team: 'England',
    odiRuns: 3159,
    testRuns: 6117,
    debutYear: 2011,
  },
  {
    name: 'Quinton de Kock',
    team: 'South Africa',
    odiRuns: 6176,
    testRuns: 3300,
    debutYear: 2012,
  },
  {
    name: 'Marnus Labuschagne',
    team: 'Australia',
    odiRuns: 1103,
    testRuns: 3882,
    debutYear: 2018,
  },
  {
    name: 'Jos Buttler',
    team: 'England',
    odiRuns: 4823,
    testRuns: 2907,
    debutYear: 2011,
  },
  {
    name: 'Kusal Mendis',
    team: 'Sri Lanka',
    odiRuns: 3220,
    testRuns: 4472,
    debutYear: 2015,
  },
  {
    name: 'Shubman Gill',
    team: 'India',
    odiRuns: 2271,
    testRuns: 1154,
    debutYear: 2019,
  },
  {
    name: 'Tamim Iqbal',
    team: 'Sri Lanka',
    odiRuns: 8313,
    testRuns: 5082,
    debutYear: 2007,
  },
  {
    name: 'Rohit Sharma',
    team: 'India',
    odiRuns: 10112,
    testRuns: 3677,
    debutYear: 2007,
  },
  {
    name: 'Ravindra Jadeja',
    team: 'India',
    odiRuns: 2526,
    testRuns: 2757,
    debutYear: 2009,
  },
  {
    name: 'Mitchell Starc',
    team: 'Australia',
    odiRuns: 1188,
    testRuns: 1807,
    debutYear: 2010,
  },
  {
    name: 'Trent Boult',
    team: 'New Zealand',
    odiRuns: 289,
    testRuns: 855,
    debutYear: 2011,
  },
  {
    name: 'Pat Cummins',
    team: 'Australia',
    odiRuns: 324,
    testRuns: 1013,
    debutYear: 2011,
  },
  {
    name: 'Stuart Broad',
    team: 'England',
    odiRuns: 529,
    testRuns: 3656,
    debutYear: 2006,
  },
  {
    name: 'Jasprit Bumrah',
    team: 'India',
    odiRuns: 77,
    testRuns: 133,
    debutYear: 2016,
  },
  {
    name: 'Sam Curran',
    team: 'England',
    odiRuns: 592,
    testRuns: 815,
    debutYear: 2018,
  },
  {
    name: 'Tim Southee',
    team: 'New Zealand',
    odiRuns: 726,
    testRuns: 1991,
    debutYear: 2008,
  },
  {
    name: 'Hardik Pandya',
    team: 'India',
    odiRuns: 1518,
    testRuns: 532,
    debutYear: 2016,
  },
  {
    name: 'Matt Henry',
    team: 'New Zealand',
    odiRuns: 187,
    testRuns: 272,
    debutYear: 2014,
  },
  {
    name: 'Shaun Marsh',
    team: 'Australia',
    odiRuns: 2773,
    testRuns: 2265,
    debutYear: 2008,
  },
  {
    name: 'Ricky Ponting',
    team: 'Australia',
    odiRuns: 13704,
    testRuns: 13378,
    debutYear: 1995,
  },
  {
    name: 'Jacques Kallis',
    team: 'South Africa',
    odiRuns: 11579,
    testRuns: 13289,
    debutYear: 1995,
  },
  {
    name: 'AB de Villiers',
    team: 'South Africa',
    odiRuns: 9577,
    testRuns: 8765,
    debutYear: 2004,
  },
  {
    name: 'Michael Clarke',
    team: 'Australia',
    odiRuns: 7981,
    testRuns: 8643,
    debutYear: 2003,
  },
  {
    name: 'Andrew Flintoff',
    team: 'England',
    odiRuns: 3394,
    testRuns: 3845,
    debutYear: 1998,
  },
  {
    name: 'Kevin Pietersen',
    team: 'England',
    odiRuns: 4440,
    testRuns: 8181,
    debutYear: 2004,
  },
  {
    name: 'Alastair Cook',
    team: 'England',
    odiRuns: 3204,
    testRuns: 12472,
    debutYear: 2006,
  },
  {
    name: 'Graeme Smith',
    team: 'South Africa',
    odiRuns: 6989,
    testRuns: 9265,
    debutYear: 2002,
  },
  {
    name: 'Hashim Amla',
    team: 'South Africa',
    odiRuns: 8113,
    testRuns: 9282,
    debutYear: 2004,
  },
  {
    name: 'Faf du Plessis',
    team: 'South Africa',
    odiRuns: 5507,
    testRuns: 4163,
    debutYear: 2011,
  },
  {
    name: 'Brendon McCullum',
    team: 'New Zealand',
    odiRuns: 6083,
    testRuns: 6453,
    debutYear: 2002,
  },
  {
    name: 'Ross Taylor',
    team: 'New Zealand',
    odiRuns: 8607,
    testRuns: 7683,
    debutYear: 2006,
  },
  {
    name: 'Dale Steyn',
    team: 'South Africa',
    odiRuns: 365,
    testRuns: 1250,
    debutYear: 2004,
  },
  {
    name: 'Anil Kumble',
    team: 'India',
    odiRuns: 938,
    testRuns: 2506,
    debutYear: 1990,
  },
  {
    name: 'Glenn McGrath',
    team: 'Australia',
    odiRuns: 115,
    testRuns: 641,
    debutYear: 1993,
  },
  {
    name: 'Brett Lee',
    team: 'Australia',
    odiRuns: 1176,
    testRuns: 1451,
    debutYear: 1999,
  },
  {
    name: 'Shane Warne',
    team: 'Australia',
    odiRuns: 1018,
    testRuns: 3154,
    debutYear: 1992,
  },
  {
    name: 'Muttiah Muralitharan',
    team: 'Sri Lanka',
    odiRuns: 674,
    testRuns: 1261,
    debutYear: 1992,
  },
  {
    name: 'Mahela Jayawardene',
    team: 'Sri Lanka',
    odiRuns: 12650,
    testRuns: 11814,
    debutYear: 1997,
  },
  {
    name: 'Kumar Sangakkara',
    team: 'Sri Lanka',
    odiRuns: 14234,
    testRuns: 12400,
    debutYear: 2000,
  },
  {
    name: 'Chris Gayle',
    team: 'West Indies',
    odiRuns: 10480,
    testRuns: 7214,
    debutYear: 1999,
  },
  {
    name: 'Brian Lara',
    team: 'West Indies',
    odiRuns: 10405,
    testRuns: 11953,
    debutYear: 1990,
  },
  {
    name: 'Shivnarine Chanderpaul',
    team: 'West Indies',
    odiRuns: 8778,
    testRuns: 11867,
    debutYear: 1994,
  },
  {
    name: 'Jason Holder',
    team: 'West Indies',
    odiRuns: 2042,
    testRuns: 2712,
    debutYear: 2013,
  },
];
